### ISSUE TITLE
Would you like to add python 2.7 support?

### ISSUE THREAD

**Issue by hyan15** [JaredLGillespie/proxyscrape#1]
Would you like to add python 2.7 support? I can open a pr

**Comment by JaredLGillespie** [comment]
Sure, that sounds like a great idea. If you get a PR going, I'll take a look at it and will help get that integrated.

**Comment by hyan15** [comment]
PR has been added: #2

**Comment by JaredLGillespie** [comment]
#2 has been merged. Tagging as version 0.1.1.
